services:

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - "5430:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: todolist
      POSTGRES_HOST_AUTH_METHOD:
    command: [ "postgres", "-c", "listen_addresses=*" ]
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  pg_data:
